edited firebase-deployment github action

diff --git a/.github/workflows/firebase-deploy.yml b/.github/workflows/firebase-deploy.yml
--- a/.github/workflows/firebase-deploy.yml
+++ b/.github/workflows/firebase-deploy.yml
@@ -21,10 +21,16 @@ jobs:
       - name: Install Firebase CLI
         run: npm install -g firebase-tools
 
+      - name: Set up GreenSock Auth Token
+        run: echo "//npm.greensock.com/:_authToken=${{ secrets.GSAP_TOKEN }}" >> ~/.npmrc
+
+      - name: Install Dependencies and Build
+        run: |
+          npm install
+          npm audit fix || true # This will try to fix vulnerabilities but not fail the build
+          npm run build
+
       - name: Deploy to Firebase
         env:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
-        run: |
-          npm install
-          npm run build
-          firebase deploy --only hosting
+        run: firebase deploy --only hosting
